### ISSUE TITLE
Additional push in a Dependabot PR does not trigger actions

### ISSUE THREAD

**Issue by nak3** [knative/infra#200]
/area test-and-release
/kind bug

As got the answerd in https://github.com/orgs/community/discussions/62346 (Thanks @kvmware), we need to use `Personal Access Token` or `GitHub App token` to trigger github action when dependabot sends additional PR (after running hack script).

Should we add a "Personal Access Token" or "GitHub App token" for this? Or is there any other ideas?

__Note__ There is one workaround which we can close&re-open the dependabot to trigger the githubaction.

**Comment by dprotaso** [comment]
/assign @kvmware 

Can we look into using the prow bot's token (the one that does cherry-picks to also do these PR changes) ?

**Comment by kvmware** [comment]
Yes, but I still think reusing a github app would be better even if it is prow's. @upodroid Do you have a suggestion?

Notes:
- Action in question is https://github.com/knative/pkg/blob/main/.github/workflows/knative-dependabot.yaml
- example github app approach https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/making-authenticated-api-requests-with-a-github-app-in-a-github-actions-workflow

**Comment by dprotaso** [comment]
@krsna-m is there any action here? seems like there was no resolution based on the discussion above
