### ISSUE TITLE
Branch protection rules should only apply to main and release-* branches

### ISSUE THREAD

**Issue by dprotaso** [knative/infra#203]
In various repos I see lots of `someuser-patch-1` 

Generally people should be making edits in forks and then making PRs but that's a separate issue.

We have a branch protector job or something that marks these patch branches as protected when they shouldn't be.

Thus to clean up the branch it requires someone to delete the branch protect rules and then the branch which is tedious.

**Comment by kvmware** [comment]
Agree with the forks. 
The *_patch is usually because of edits done via gui. We should maybe put some restrictions on branch names.

Will look into branch protection rules.
/assign

**Comment by kvmware** [comment]
![image](https://github.com/knative/infra/assets/84356882/7cec10bf-6cce-4a37-9e52-5d1f57571de9)
Could you please give an example. The settings (attached) look like they are only protecting what we want.

However, it is a bit poorly documented if it is protect everything except `exclude` or not and why is there a `include/exclude` etc.

Also, do you have an example repo you are seeing this on you can link for testing?

**Comment by dprotaso** [comment]
docs has a bunch of branches - https://github.com/knative/docs/branches/all

**Comment by dprotaso** [comment]
infra has one - though I can delete it :hmm:
https://github.com/knative/test-infra/branches/all

**Comment by dprotaso** [comment]
let me test out a new one

**Comment by kvmware** [comment]
It also does not help if you have a management/admin acct like most people on Productivity and you might as well

**Comment by kvmware** [comment]
The branch protector rules look fine though so unless we can get an actual issue with deleting the branches maybe close it out?

**Comment by dprotaso** [comment]
ok i made a new branch in serving - I just ran the branch protector prow job to see if it adds it

https://github.com/knative/serving/branches/active

https://prow.knative.dev/view/gs/knative-prow/logs/ci-knative-infra-branchprotector/1706366540468719616

Maybe the branch protector doesn't _remove_  protections - so these older branches are still locked down

**Comment by dprotaso** [comment]
OK cool it works as expected - I guess the older branch protections aren't dropped

> msg":"knative/serving=dprotaso-patch-1: not included"
